---
dry_scaffold:
  args:
    actions: index,show,new,edit,create,update,destroy
    formats: html,js,xml,json
  options:
    formtastic: true
    resourceful: true
    pagination: false
    layout: false
    views: true
    helpers: true
    tests: true
    controller_tests: true
    test_unit: false
    shoulda: false
    rspec: true
    fixtures: false
    fgirl: true
    machinist: false
    object_daddy: false
dry_model:
  options:
    migration: true
    timestamps: true
    tests: true
    test_unit: false
    shoulda: false
    rspec: true
    fixtures: false
    fgirl: true
    machinist: false
    object_daddy: false

